# Generated by Django 4.2.2 on 2023-08-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_social_insta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_fb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
