# Generated by Django 4.2.2 on 2023-08-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Category',
        ),
    ]
