# Generated by Django 4.2.2 on 2023-09-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof_image',
            field=models.ImageField(blank=True, default='profiles/user_default.png', null=True, upload_to='profiles/'),
        ),
    ]
