# Generated by Django 4.2.2 on 2023-08-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username_alter_profile_name'),
        ('projects', '0004_project_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Product',
        ),
    ]
