# Generated by Django 4.2.2 on 2023-08-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_product_options_rename_project_review_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
    ]
